### PR TITLE
Added the flexible language path in `TranslationConfiguration`

### PR DESCRIPTION
**Pull request by derian-all-win-software**
### Description

This PR added the absoluteLanguageDirectory parameter in the TranslationConfiguration type to define a custom language directory if needed.

By default, if the Laravel version is lower than v9, the directory is `resources/lang`. Otherwise, the directory will be `lang/` in the root project. This validation causes a problem if the project version is higher than v9 and it saves the localization files in the `resources/lang` directory. A simple solution is to create a symbolic link from the `resources/lang` directory to the `lang/` directory in the root project. However, ideally, people should configure a custom directory if needed from the Vite configuration to avoid creating unnecessary processes to solve problems with the language directory.

- Added the `absoluteLanguageDirectory` param in `TranslationConfiguration` type.
- Refactored code in `determineLaravelVersion` function.
- Refactored code in `Loader` file to separate and improve the logic.
- Created a file for `mergeDeep` function.

### Testplan

- I ran this code in a code sandbox in Javascript and Typescript languages.

### CODE REVIEW

**Review by lionslair — APPROVED** [review]
Looks good I will I just need another to check. will follow up

**Review by lionslair — APPROVED** [review]

**Comment by lionslair** [comment]
Yeah still waiting for college to look it over too

**Review by immersedone — APPROVED** [review]

**Comment by PadowYT2** [comment]
I don't think this works, typescript forced me to add .js at the end of the import. But you haven't added it here

**Comment by immersedone** [comment]
@PadowYT2 see commit: https://github.com/dcodegroup/vite-plugin-laravel-translations/commit/c703d81287e2562fae4845fa6d3f86f1e2f9fb11. Released as [v0.2.3](https://www.npmjs.com/package/vite-plugin-laravel-translations/v/0.2.3) on NPM.

**Pull request merged**
